export enum ElementCategory {
    Flowchart = "Flowchart",
    SequenceDiagram = "SequenceDiagram",
    ClassDiagram = "ClassDiagram",
    StateDiagram = "StateDiagram",
    EntityRelationshipDiagram = "EntityRelationshipDiagram",
    UserJourneyDiagram = "UserJourneyDiagram",
    GanttChart = "GanttChart",
    PieChart = "PieChart",
    RequirementDiagram = "RequirementDiagram",
    GitGraph = "GitGraph",    
    Mindmap = "Mindmap",
    Timeline = "Timeline",
    C4Diagram = "C4Diagram",
    QuadrantChart = "QuadrantChart",
    SankeyDiagram = "SankeyDiagram",
    XyChart = "XyChart",
    Kanban = "Kanban",
    Architecture = "Architecture",
    Block = "Block",
    Packet = "Packet"
}